services:
  backend:
    build:
      context: ./pwvault-back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    build:
      context: ./pwvault-front
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
